name: GitHub-Profile-Summary-Cards

on:
  create:
  push:
  schedule: # execute every Monday At 05:30 on
    - cron: "30 5 * * MON"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate

    steps:
      - uses: actions/checkout@v2
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          USERNAME: ${{ github.repository_owner }}
